name: Build and Push Next.js Docker Image

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build the Docker image with the environment variable
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_ADDRESS=${{ secrets.NEXT_PUBLIC_API_ADDRESS }} \
            -t dms-web-client:latest .
      
      # List Docker images
      - name: List Docker images
        run: docker images
      
      # Tag the Docker image based on branch
      - name: Tag Docker image
        run: |
          if [[ "${{ github.ref_name }}" == "release" ]]; then
            docker tag dms-web-client:latest vanotsintsabadze/dms-web-client:prod
          else
            docker tag dms-web-client:latest vanotsintsabadze/dms-web-client:local
          fi
      
      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          if [[ "${{ github.ref_name }}" == "release" ]]; then
            docker push vanotsintsabadze/dms-web-client:prod
          else
            docker push vanotsintsabadze/dms-web-client:local
          fi
